name: Delete Branch After Merge to Master

on:
  push:
    branches:
      - master

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get the name of the merged branch
        id: get-branch
        run: |
          # Extract the source branch name from the pull request merge commit
          MERGED_BRANCH=$(git log --merges -1 --pretty=%b | grep -oP "(?<=from )[^\s]+")
          echo "Merged branch: $MERGED_BRANCH"
          echo "merged_branch=$MERGED_BRANCH" >> $GITHUB_OUTPUT

      - name: Delete the merged branch
        run: |
            if [[ -n "${{ steps.get-branch.outputs.merged_branch }}" ]]; then
            git push origin --delete ${{ steps.get-branch.outputs.merged_branch }}
            echo "Deleted branch: ${{ steps.get-branch.outputs.merged_branch }}"