name: Delete Branch After Merge to Master

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  push:
    branches:
      - master

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get the name of the merged branch
        id: get-branch
        run: |
          # Get the pull request's source branch name using the merge commit
          MERGED_BRANCH=$(git log --merges -1 --pretty=%b | grep -oP '(?<=from )\S+')

          # Check if the branch was found
          if [ -z "$MERGED_BRANCH" ]; then
            echo "Could not extract merged branch name."
            exit 1
          fi

          echo "Merged branch: $MERGED_BRANCH"
          echo "merged_branch=$MERGED_BRANCH" >> $GITHUB_ENV

      - name: Delete the merged branch
        run: |
          if [[ -n "${{ env.merged_branch }}" ]]; then
            git push origin --delete ${{ env.merged_branch }}
            echo "Deleted branch: ${{ env.merged_branch }}"
          else
            echo "No branch to delete"
          fi